name: Deploy to VPS

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: sidikfaha/deploy-docker@v1.0.1
        with:
          docker_compose_file: docker-compose.yml
          docker_compose_command: up -d
