name: Deploy to VPS

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Configure SSH agent
      run: |
        eval $(ssh-agent -s)
        ssh-add $GITHUB_WORKSPACE/private_key
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        agent: true
        script: |
          cd /home/debian/DOCKER/skillminer
          sh script.sh
